name: AKS Helm deploy
description: Deploy application service to AKS cluster
inputs:      
  ChartPath:
    description: Chart path
    required: true
    default: helm
  ClientId:
    description: Service principal client Id
    required: true        
  ClusterName:
    description: AKS cluster name
    required: true
  ClusterNamespace:
    description: AKS namespace
    required: true
  ClusterResourceGroupName:
    description: AKS cluster resource group name
    required: true
  KubeloginVersion:
    description: Kubelogin version
    required: true
    default: "v0.0.13"
  ReleaseName:
    description: Helm release name
    required: true
  SubscriptionId:
    description: Service principal subscription Id
    required: true
  TenantId:
    description: Service principal tenant Id
    required: true

runs:
  using: "composite"
  steps:
    - name: "Login with SPN"
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.ClientId }}
        tenant-id: ${{ inputs.TenantId }}
        subscription-id: ${{ inputs.SubscriptionId }} 

    - name: "Install kube-login tool"
      shell: bash
      run: |
          curl -LO "https://github.com/Azure/kubelogin/releases/download/${{ inputs.KubeloginVersion }}/kubelogin-linux-amd64.zip"
          sudo unzip -j "kubelogin-linux-amd64.zip" -d /usr/local/bin
          rm -f "kubelogin-linux-amd64.zip"
          kubelogin --version

    - name: "Set K8s context"
      uses: Azure/aks-set-context@v2
      with:
        resource-group: ${{ inputs.ClusterResourceGroupName }}
        cluster-name: ${{ inputs.ClusterName }}
        subscription: ${{ inputs.SubscriptionId }}
        admin: "false"
        use-kubelogin: "true"

    - name: "Deploy with Helm"
      shell: bash
      env:
          CHART_PATH: ${{ inputs.ChartPath }}
          RELEASE: ${{ inputs.ReleaseName }}
          NAMESPACE: ${{ inputs.ClusterNamespace }}
      run: |
          helm template -n ${NAMESPACE} ${RELEASE} ${CHART_PATH} --values ${CHART_PATH}/values-override.yaml
          helm upgrade --install -n ${NAMESPACE} ${RELEASE} ${CHART_PATH} --values ${CHART_PATH}/values-override.yaml --timeout 3m0s --wait